### ISSUE TITLE
clone student-repos fails if any repo exits in target dir

### ISSUE THREAD

**Issue by NukeManDan** [github/gh-classroom#14]
Presently, once a failure happens you have to _start over without any repos cloned - there is not skipping of existing repos possible. 

- I want to re-run in a dir with _some_ repos cloned but the process was interrupted.
- I want to update all repos that exist to latest `main` (default) branch for all repos

**Comment by shanep** [comment]
@NukeManDan Just submitted a pull request to that fixes this issue. I was having the same problem :)

**Comment by shanep** [comment]
@zrdaley can we close this now that my PR has been fully merged :)

**Comment by zrdaley** [comment]
fixed by https://github.com/github/gh-classroom/pull/39
