### ISSUE TITLE
Add documentation for REST Api to facilitate new feature development.

### ISSUE THREAD

**Issue by shanep** [github/gh-classroom#33]
There are a few features I would like to add regarding the classroom roster. However, I don't see information on https://docs.github.com/en/rest about what endpoints are available or response schema.  

Is it possible to get API documentation for the classroom API? If the documentation already exists and I am just looking in the wrong place can we add a link in the README to the API documentation?

**Comment by RyanHecht** [comment]
Hey! This is on our radar, and we're looking into making more information about the Classroom API public soon! :)

**Comment by shanep** [comment]
@RyanHecht This is awesome! With documentation on the endpoints there are SOOOO many cool features I would like to add :) 

Keep up the good work it is much appreciated!

**Comment by RyanHecht** [comment]
Hey @shanep! 

Our API documentation is live here: https://docs.github.com/en/rest/classroom/classroom?apiVersion=2022-11-28

And @zrdaley wrote an awesome blog post diving into how to contribute to the extension! https://github.blog/2023-09-25-calling-all-teachers-learn-how-to-build-new-commands-on-the-github-classroom-cli/
