### ISSUE TITLE
Missing repos

### ISSUE THREAD

**Issue by ben-marlin** [github/gh-classroom#35]
I'm very new to GitHub Classroom, but I can't see where this issue has been addressed. 

With `gh classroom clone student-repos`, I get 30 repos from a class of 56. Those that get cloned include some who have submitted and some who have not. Likewise with those which are missing.

Any idea what could be at fault?

**Comment by shanep** [comment]
Hi, 

The downloader defaults to just 30. You can download more using the **--per-page** command line flag. With the example below we set the number of repos to download to 100 which should cover all your students :)

`gh classroom clone student-repos --per-page 100`

You can list all the options like this:

```
shane:classroom$ gh classroom clone student-repos --help        
Clone student repos for an assignment into a directory.

By default, the student repos are cloned into the current directory a directory named after the assignment slug. To clone into a different directory, use the --directory flag.

If the directory does not exists, it will be created.

Usage:
  classroom clone student-repos [flags]

Flags:
  -a, --assignment-id int   ID of the assignment
  -d, --directory string    Directory to clone into (default ".")
  -h, --help                help for student-repos
      --page int            Page number (default 1)
      --per-page int        Number of accepted assignments per page (default 30)
```

**Comment by NukeManDan** [comment]
I (and every faculty member working with this tool) ran into this footgun as well - I would think a more sensible default be to do all students. Pages make no sense from the CLI - but do from the GUI, IMHO.

**Comment by shanep** [comment]
@NukeManDan I have a fix for this issue but I am currently blocked by issue #34 maybe @ryanhecht can help with getting this resolved?

**Comment by shanep** [comment]
Hi @NukeManDan and @ben-marlin I have summited a pull request #37  to address this. It seems to work on my end however if you would like to pull it down and test it out maybe that will help @RyanHecht merge it into main :)

**Comment by shanep** [comment]
@RyanHecht and @zrdaley With pr https://github.com/github/gh-classroom/pull/37 now merged on main can this issue be closed?

**Comment by shanep** [comment]
@NukeManDan  and @ben-marlin  https://github.com/github/gh-classroom/pull/37 was merged which allows you to clone all repos using `gh classroom clone student-repos --all`

You will need to pull in the latest release ([v.0.1.9](https://github.com/github/gh-classroom/releases/tag/v0.1.9)) first using `gh extension upgrade classroom`

**Comment by ben-marlin** [comment]
Thank you, friend!

*Ben Marlin (he / him / his)*
Associate Professor, Chair of Mathematics
Guilford College
5800 West Friendly Avenue
Greensboro, North Carolina  27410

Office: Bauman 210H   Phone: 336.316.2478
Fall 2023 Office Hours:
     Tuesday & Thursday 10:30-11:20 Monday & Friday 1:30-2:20
     For Zoom appointments, consult my calendar
<https://calendar.google.com/calendar/u/0?cid=Ym1hcmxpbkBndWlsZm9yZC5lZHU>
and email a request.

**Comment by zrdaley** [comment]
@shanep yes! thank you again for resolving this issue!
