### ISSUE TITLE
Feature request: indicate that more pages exist in clone student-repos 

### ISSUE THREAD

**Issue by kapravel** [github/gh-classroom#4]
It took me a second to realize that not all of the repos were downloaded, but only the first page (30 repositories). It would be nice to print the number of pages or some sort of message that indicates that not all repositories were downloaded (30/100). 

For reference, here's what worked for me:
`gh classroom clone student-repos --per-page 100`

**Comment by girodg** [comment]
Thank you. I didn't see your issue and entered my own without seeing your solution.

**Comment by RyanHecht** [comment]
Hi! We're going to look into ways we can make this more apparent in-product in addition to having it called out in docs

**Comment by shanep** [comment]
@RyanHecht and @zrdaley With pr #37 now merged on main can this issue be closed?

**Comment by zrdaley** [comment]
@shanep I think we still want to add more logging to the `clone` command in order to close this issue.

**Comment by shanep** [comment]
@zrdaley No problem on the more logging, Added it in with pr #46 :)

**Comment by shanep** [comment]
Hi @zrdaley so with the additional logging and all code merged can we consider this issue closed?

**Comment by zrdaley** [comment]
Yes, thank you @shanep!

**Comment by doctorscott** [comment]
I cannot get the per page to work. I just get a "HTTP 500: Server Error" with the assignment link:
(https://api.github.com/assignments/540986/accepted_assignments?page=1&per_page=99)

I updated cli and still this error. Honestly, I have no idea why you would limit it to 30 assignments in the first place. And updating the documentation is not a sufficient fix.
