### ISSUE TITLE
Feature Request: Add `download-submissions` Command to GitHub Classroom CLI for Bulk Download of Student Submissions

### ISSUE THREAD

**Issue by christosgalano** [github/gh-classroom#43]
**Is your feature request related to a problem? Please describe.**
I would like to highlight a specific issue: instructors often find it challenging and time-consuming to individually access and download student submissions in GitHub Classroom. 

**Describe the solution you'd like**
I would like to propose the addition of a download-submissions command to the GitHub Classroom CLI that enables instructors to efficiently retrieve and save all student submissions for a specific assignment within a classroom. This command will use GET requests, including the "List accepted assignments for an assignment" API endpoint, to retrieve student repository information. Then, it should proceed to clone or download those repositories to a specified output directory. This feature would significantly streamline the process of accessing and reviewing student work.

**Describe alternatives you've considered**
As an alternative, instructors can manually clone each student's repository, but this process is time-consuming and prone to errors, especially when dealing with large classrooms. Automating this task through a dedicated command would greatly enhance the user experience.

**Additional context**
This enhancement would be highly beneficial for instructors who use GitHub Classroom for managing assignments and grading. It would improve workflow efficiency and reduce the administrative overhead of accessing student submissions, ultimately leading to a more positive experience for educators using GitHub Classroom.

**Comment by shanep** [comment]
Hi @christosgalano,

I am not sure if I understand what you are asking. This already exists with the command `gh classroom clone student-repos`

-Shane
