### ISSUE TITLE
Invitation Links are Broken

### ISSUE THREAD

**Issue by ptyork** [github/gh-classroom#6]
Currently it appears that the assignment invitation links point to a URL of form //github.com/assignment-invitations/[somelongid]. This leads to a 404 page.

Working links appear to be of the form //classroom.github.com/a/[someshortid]

**Comment by bpurinton** [comment]
Yes, this would be great to fix! See my discussion comment:

https://github.com/community/Global-Campus-Teachers/discussions/220
