### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by gedw99** [github/gh-classroom#61]
Am using this with students.

i work with scientists and scientific research organisations. Code is a first class part of science these days and a GIU can help them with onboarding until they are comfortable on the cli .

So I am contemplating adding a gui that works with this cli code .

would that be ok as a PR ? 

Would be happy to discuss the methodology / implementation but it basically a custom gui that provides the same functionality and data as the cli but as a web and native app. The idea is to make it as easy as possible for non coders to work with GitHub classrooms and drop down to the cli when they gain more confidence .

it would use the same call paths so all code coverage would be exercised and written in golang.

**Comment by RyanHecht** [comment]
This sounds like it would be an excellent companion project (and I'd love to see it happen!), but we probably will not merge a PR to add a GUI component to this codebase, which is an extension for the GitHub CLI. You could definitely use the public API's (and even possibly an embedded GitHub CLI client) to make that happen!
