### ISSUE TITLE
[Bug] Incorrect submission number in CLI.

### ISSUE THREAD

**Issue by ashwinexe** [github/gh-classroom#63]
**Describe the bug**
Classroom CLI seems to show submission as **zero** while the Classroom webpage shows **Non zero** submissions.

**Expected Behavior**
Classroom CLI should show the same number of submissions as displayed on the webpage dashboard

**Additional Context**

I was going through GitHub Octernships submission of our latest partner and used classroom cli to check stats. For some reason, submission shown in webpage (screenshot attached) shows 15 submissions while CLI shows 0 (screenshot attached)
Upon further investigation, it seems every classroom shows up 0 submissions under cli while it has a number on the classroom page.

**Screenshots**

Webpage
![Screenshot 2023-12-01 at 3 59 22 PM](https://github.com/github/gh-classroom/assets/53075480/f5dc043e-a703-4ceb-82fc-24646443b2c9)

CLI
![Screenshot 2023-12-01 at 3 59 59 PM](https://github.com/github/gh-classroom/assets/53075480/2d188677-454b-407e-807c-499c8a876a32)

**Comment by nixpad** [comment]
@ashwinexe 👋 thank you for submitting this issue! cc @RyanHecht for visibility and prioritization.

**Comment by DiegoPerezGarcia** [comment]
I've investigated and I have the same issue. I think it's more a server problem with the endpoint more than a problem with the extension it self.

I did a GET request to https://api.github.com/assignments/353859 and received "submissions: 0" when the assignment have 9 submissions.

<img width="556" alt="Captura de pantalla 2024-04-01 a las 20 22 53" src="https://github.com/github/gh-classroom/assets/72458271/1bc54a87-1ad8-4cad-ab12-5e942857cdac">

<img width="1276" alt="Captura de pantalla 2024-04-01 a las 20 25 05" src="https://github.com/github/gh-classroom/assets/72458271/80b1b890-b081-4e99-809d-9d6365ff6b49">
