### ISSUE TITLE
[BUG]: AppData\Local\GitHub CLI\extensions\gh-classroom\gh-classroom.exe: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by AAtuan** [github/gh-classroom#68]
Thanks for taking the time to fill out this out! :bow:
By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/github/gh-copilot/blob/main/CODE_OF_CONDUCT.md).

### What happened?
_What did you do? What happened? What did you expect to happen?_
I installed the github cli on my laptop, which is running windows 11. Then I installed the gh classroom extension, which is the one I need for grading, but I always get this error and I don't know how to fix it. I was expecting to see my classroom list to then clone some repos.

### Versions
_What versions of the relevant software are you running?_
_For example: `gh v2.37.0, gh-copilot v0.5.2-beta`_
latest version

### Relevant terminal output
_Please copy and paste any relevant terminal output._
_Please check your output before submission to ensure sensitive information is redacted._
AppData\Local\GitHub CLI\extensions\gh-classroom\gh-classroom.exe: %1 is not a valid Win32 application

**Comment by nixpad** [comment]
@andyfeller thank you for the suggestions! Closing as stale and done.
