### ISSUE TITLE
Feature request: pulling student repos

### ISSUE THREAD

**Issue by physcrowley** [github/gh-classroom#8]
I love that these scripts exist! ...but it would be more complete if there was also a `pull` command. 

I made my own Python versions two years ago using the dowloaded CSV rosters and have now adjusted the target folder name to match the gh classroom naming convention. I only use three commands in my own scripts : 
1. clone student repos
2. report work done on student repos (source code file count, commit count)
3. pull student repos

1 and 2 have equivalents in the gh classroom CLI, but 3 is missing. 

I use 3 because many of my assignments take several days and I like seeing progress in real time from my own IDE so I can follow-up with students struggling before the deadline. The IDE's synchronise command is not clearly repo/project or workspace specific so I need a tool that explicitly iterates / recurses through each student repo to make sure that I haven't missed any student commits when doing these check-ins.

**Comment by shanep** [comment]
@physcrowley I also wanted this so I built it and summited a pull request #39 . If you want to pull it down and test it out that would be awesome :)

**Comment by shanep** [comment]
Hi @zrdaley  can we close this issue now that pr #39 has been merged :)

**Comment by zrdaley** [comment]
Yes, thank you @shanep!

**Comment by physcrowley** [comment]
Thanks for the great work @shanep !
