### ISSUE TITLE
Assignment with templates

### ISSUE THREAD

**Issue by pmcstjean** [github/gh-classroom#80]
Hi, 

I just tried creating a new classroom to experiment the new fork feature (been opting out last year). I next created an assigment with a template like I used to do. When my test student click the link, it joins the classroom like it should but I receive a 406 error when accepting the assignment. I don't remember the exact message but it was something like "teach need to edit assignment..". It seems that a fork repo has been created but the student can't access it and I can't delete this assignment anymore (errror 406).

**Comment by vnijs** [comment]
Sounds very similar to the issue I just posted. 

https://github.com/github/gh-classroom/issues/81

**Comment by pmcstjean** [comment]
> Sounds very similar to the issue I just posted.
> 
> #81

Definitely the same error message ! Seems to happen only with templates, though.
