### ISSUE TITLE
500 error when students accept assignments

### ISSUE THREAD

**Issue by duckkyzTeacher** [github/gh-classroom#82]
When students accept an assignment they get a 500 error

**Comment by duckkyzTeacher** [comment]
or they get a page that says "You accepted the assignment, Converter . We're configuring your repository now. This may take a few minutes to complete. Refresh this page to see updates." but never loads

**Comment by josephconroy** [comment]
I am experiencing a similar issue. When either student or instructor accepts an assignment, we are confronted with a 500: Internal Server Error screen. When I then check the Github Classroom, I can see that the repository has been created and populated, but the students do not have permission to see or access it. I have far too many students in my course to manually assign permissions for every assignment, so that is not a viable workaround.

What is causing this, and what workarounds could I use if no solution is available?

**Comment by syifan** [comment]
Same problem here. I am teaching the first in-class assignment for the semester, but we cannot continue.

**Comment by josephconroy** [comment]
@tarebyte released a bug fix that resolved a [similar problem back in 2017](https://github.com/github-education-resources/classroom/issues/1117), but I am not sure if this is a similar scenario or simply user error.

**Comment by AncestorComposition** [comment]
I'm seeing the same thing.  This is a potential showstopper.  Please resolve ASAP.

**Comment by darivadilacuna** [comment]
I am having the same issue. With old and new assignments, the problem is the same.

**Comment by unclej** [comment]
I am also having this issue; following.

**Comment by gdcho** [comment]
+1

**Comment by jeffbcit** [comment]
having the same 500 error issue when accepting an assignment and attempting to clone a repo

**Comment by JeremyBannon** [comment]
Having the same issue. --Following

**Comment by fresh-install** [comment]
same issue

**Comment by offthewallace** [comment]
same issue

**Comment by RobertDGordon** [comment]
Has anyone checked the console logs to see if there are more details to be shared about the error?

**Comment by BrityHemming** [comment]
Also experiencing the same issue with my students

**Comment by duckkyzTeacher** [comment]
> Has anyone checked the console logs to see if there are more details to be shared about the error?

This is an issue in github classroom on the web interface, my students dont use git via command line so I cannot comment on any additional details in the logs.

**Comment by duckkyzTeacher** [comment]
Seems more likely that some backend change is the cause seeing that it is widespread and effecting previously working assignments.

In either case I have submitted an official ticket and hope that it will be resolved soon.

**Comment by unclej** [comment]
Worked for me this morning ... no changes.

**Comment by syifan** [comment]
Same here. It was working yesterday in the evening. Just a large number of repos created in the organization without linking with an assignment during the problematic period. Now students can accept the assignment again without any problem.

**Comment by duckkyzTeacher** [comment]
GitHub rolled out a fix last night. It is now working for me. Going to close this but reopen if you find it still doesnt work.
